### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by Mollayo** [jamesturton/shelly-dimmer-stm32#20]
@jamesturton Thank you for putting your source code for the STM32 firmware. I have one question. The two functions ([tim1_cc_isr](https://github.com/jamesturton/shelly-dimmer-stm32/blob/56598041a8baa8b8faceb1f4ab2915ff8af3b9e4/src/main.c#L769)  and [exti2_3_isr](https://github.com/jamesturton/shelly-dimmer-stm32/blob/56598041a8baa8b8faceb1f4ab2915ff8af3b9e4/src/main.c#L884)) are called for the zero crossing of the voltage. But it there a way to detect if the voltage is negative or positive ? My plan is to develop a firmware for this [protocol](http://lycees.ac-rouen.fr/maupassant/Melec/co/2melec/co/Chauffage/webMob/res/10_03_ill_ordre_fil_pilote.png).

**Comment by jamesturton** [comment]
It is the `exti2_3_isr` function which is called at the zero crossing point. So when this is called you can check the pin directly if it high or low ([like I have done here](https://github.com/jamesturton/shelly-dimmer-stm32/blob/56598041a8baa8b8faceb1f4ab2915ff8af3b9e4/src/main.c#L899)) to see if it is high or low. I'm not sure if high on that pin means positive or negative - you will have to check that!

**Comment by Mollayo** [comment]
Thank you !
