### ISSUE TITLE
Mqqt

### ISSUE THREAD

**Issue by To0wnn** [jamesturton/shelly-dimmer-stm32#28]
Hi,

The following rules i have but it is not updating mqtt somehow any idea?

Rule1 On Switch1#State=2 Do Power TOGGLE  ENDON On Switch2#State=2 Do Power TOGGLE ENDON
Rule2 On Switch1#State=4 Do Dimmer + ENDON On Switch2#State=4 Do Dimmer - ENDON
Rule3 On Switch1#State=8 Do Dimmer 100 ENDON On Switch2#State=8 Do Dimmer 10 ENDON

**Comment by jamesturton** [comment]
Hey @To0wnn!
I'm guessing you are using [Tasmota](https://github.com/arendst/Tasmota) on your hardware? You are best asking the question [there](https://github.com/arendst/Tasmota/issues/new/choose) as this repo only deals with the firmware on the STM32, not Tasmota running on the ESP8266.
