### ISSUE TITLE
Shelly Dimmer 2 Module  Tasmota  Upload Failed  Invalid file signature

### ISSUE THREAD

**Issue by jannodeluxe** [jamesturton/shelly-dimmer-stm32#8]
I get the following error when trying to flash the 51.5 FW:

Shelly Dimmer 2 Module
Tasmota
Upload Failed
Invalid file signature

Upgraded to 9.1.0.2
console reset 5
then tried to flash the bin file

**Comment by jamesturton** [comment]
@jannodeluxe Have you followed the instructions here: https://templates.blakadder.com/shelly_Dimmer_2.html
You must set the template before uploading new firmware.

**Comment by jannodeluxe** [comment]
hi @jamesturton thanks for your fast reply. Yes I did absolutely that way.

flashed Tasmota 9.1.0.2 lite
applied template
reset 5
then tried to flash the 51.5 bin file

**Comment by jamesturton** [comment]
> flashed Tasmota 9.1.0.2 lite
> reset 5
> applied template
> then tried to flash the 51.5 bin file

The Shelly dimmer drive is not included in in the Tasmota 'lite' version. You must use the full [`tasmota.bin.gz` version](http://ota.tasmota.com/tasmota/). Please try updating to that version and set the template again.

**Comment by jannodeluxe** [comment]
That made the trick! Thanks in advanced!
